version: '3.8'

services:
  auth-service:
    build: ./auth_service
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
  api-gateway:
    build: ./api_gateway
    ports:
      - "8082:8082"
    networks:
      - app-network
    depends_on:
      - auth-service
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8081:8081"
    depends_on:
      - api-gateway
    networks:
      - app-network
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - ./auth_service/credentials/.env
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql_storage:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d auth" ]
      interval: 10s
      retries: 3
      start_period: 5s
      timeout: 5s
networks:
  app-network:
    driver: bridge
